FROM python:3.12-slim
WORKDIR /app
RUN pip install --no-cache-dir mlflow psycopg2-binary
EXPOSE 5000

CMD ["mlflow", "server", \
     "--backend-store-uri", "postgresql+psycopg2://mlflow:mlflow@postgres/mlflow", \
     "--default-artifact-root", "/mlruns", \
     "--artifacts-destination", "/mlruns", \
     "--host", "0.0.0.0", \
     "--port", "5000"]